### PR TITLE
Add filter for Apple_CONT devices

### PR DESCRIPTION
**Pull request by 1technophile**
To avoid creating unnecessary entities in the discovery

### CODE REVIEW

**Comment by checkiecheck** [comment]
cool.
Is there an easy way to get rid of all the spammed devices?
i have 2000 topics in the queue with same number of devices in HomeAssistant.

**Comment by 1technophile** [comment]
You can connect to your broker with MQTT explorer and delete the `homeassistant/sensors` topic in 2 clicks, restart the gateway and the autodiscovery of the sensors will be created again.

Note that this would also delete sensors created by other software that uses MQTT discovery

**Comment by koenvervloesem** [comment]
According to @DigiH this also needs to filter `APPLE_CONTAT`: https://github.com/theengs/gateway/pull/123#issuecomment-1497367569

**Comment by checkiecheck** [comment]
yes, saw some of those too.

btw, clearing the queues did not fully clear devices and entities, only 1200 were gone. There were 800 left. so i deleted MQTT integration and readded. now things are cleared and only usefull devices remain.

**Pull request merged**
