### PR TITLE
Add auto discovery options

### PR DESCRIPTION
**Pull request by 1technophile**
Add the auto discovery parameters to the configuration options and documentation

### CODE REVIEW

**Comment by 1technophile** [comment]
@mihsu81 would you like to review?

**Comment by mihsu81** [comment]
Apologies for not replying sooner. Had a crazy week. The options you're passing to _theengsgw.conf_ in _run.sh_ are wrong. You're removing the MQTT user and adding the other 4 values under _user_.

**Comment by 1technophile** [comment]
@mihsu81 thanks, should be better

**Comment by mihsu81** [comment]
Looks good to me. Thanks a lot. 😊

**Comment by 1technophile** [comment]
@mihsu81 can you successfully install the addon, once I add the repository, I don't see the addon in the store.

**Comment by 1technophile** [comment]
I'm testing now what's going wrong

**Comment by mihsu81** [comment]
I faced more or less the same issue. I wanted to rebuild it in order to get the updated config.json but kept getting: ```ERROR (MainThread) [supervisor.addons] Add-on 007e7788_theengsgw is not available inside store``` in the supervisor logs.
Had to uninstall the add-on, removed the repository, add again the repository and installed the add-on again.
I don't really understand what caused this issue.

**Comment by mihsu81** [comment]
It's an even easer fix. 😁 Just need to check for updates in the Add-on store.
After modifying config.json, the add-on gets a new version.
image

**Comment by 1technophile** [comment]
I was asking myself what is the best way to have version control.
And maybe when doing pip install we should have the version of the gateway indicated, and also version the addon?

**Comment by mihsu81** [comment]
Good suggestion. I'll have a look tomorrow at getting some sort of versioning in place to mimic the versioning of TGW.

**Comment by mihsu81** [comment]
@1technophile And now we have versions and releases. This will definitely make life a lot easier for whomever wants to use the add-on. 🙂

**Pull request merged**
